# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-02 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dev',
            name='job',
            field=models.CharField(default='Dev', max_length=250),
        ),
    ]
