# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-02 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dev_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='dev',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
