# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-02 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dev_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='dev',
            name='place',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dev',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dev',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
